spring:
  config:
    activate:
      on-profile: mqtt

mqtt:
  url: tcp://localhost
  port: 1883
  topic: /index
  qos: 0

rms:
  toROS: "hubilon/atcplus/rms/"
  fromROS: "hubilon/atcplus/ros/"

location:
  topic: "hubilon/atcplus/ros/location"
  qos: 0
  retain: false

event:
  topic: "hubilon/atcplus/ros/event"
  qos: 0
  retain: false

path:
  topic: "hubilon/atcplus/ros/path"
  qos: 0
  retain: false

cmdvel:
  default: "cmd_vel"
  toBridge: "wavem/atcplus/rms/cmd_vel"
  fromBridge: "wavem/atcplus/ros/cmd_vel"
  qos: 0

robotpose:
  default: "robot_pose"
  fromBridge: "wavem/atcplus/ros/robot_pose"
  qos: 0

mapservermap:
  default: "map_server/map"
  toBridge: "wavem/atcplus/rms/map_server/map"
  fromBridge: "wavem/atcplus/ros/map_server/map"
  qos: 1

odometry:
  default: "odom"
  toBridge: "wavem/atcplus/rms/odom"
  fromBridge: "wavem/atcplus/ros/odom"
  qos: 0

scan:
  default: "scan"
  toBridge: "wavem/atcplus/rms/scan"
  fromBridge: "wavem/atcplus/ros/scan"
  qos: 0

imu:
  default: "imu"
  toBridge: "wavem/atcplus/rms/imu"
  fromBridge: "wavem/atcplus/ros/imu"
  qos: 0

gps:
  default: "ublox/fix"
  toBridge: "wavem/atcplus/rms/ublox/fix"
  fromBridge: "wavem/atcplus/ros/ublox/fix"
  qos: 0

chatter:
  default: "chatter"
  toBridge: "wavem/atcplus/rms/chatter"
  fromBridge: "wavem/atcplus/ros/chatter"
  qos: 0