spring:
  config:
    activate:
      on-profile: mqtt

mqtt:
  url: tcp://localhost
  port: 1883
  topic: /index
  qos: 0

rms:
  toRosTopicFormat: "hublion/atcplus/rms/"
  fromRostopicformat: "hublion/atcplus/ros/"

cmdvel:
  requestToBridgeTopic: "wavem/atcplus/ros/cmd_vel"
  responseFromBridgeTopic: "wavem/atcplus/rms/cmd_vel"
  qos: 0

robotpose:
  responseFromBridgeTopic: "wavem/atcplus/rms/robot_pose"
  qos: 0

mapservermap:
  requestToBridgeTopic: "wavem/atcplus/ros/map_server/map"
  responseFromBridgeTopic: "wavem/atcplus/rms/map_server/map"
  qos: 1

odometry:
  requestToBridgeTopic: "wavem/atcplus/ros/odom"
  responseFromBridgeTopic: "wavem/atcplus/rms/odom"
  qos: 0

scan:
  requestToBridgeTopic: "wavem/atcplus/ros/scan"
  responseFromBridgeTopic: "wavem/atcplus/rms/scan"
  qos: 0

imu:
  requestToBridgeTopic: "wavem/atcplus/ros/imu"
  responseFromBridgeTopic: "wavem/atcplus/rms/imu"
  qos: 0

ubloxfix:
  requestToBridgeTopic: "wavem/atcplus/ros/ublox/fix"
  responseFromBridgeTopic: "wavem/atcplus/rms/ublox/fix"
  qos: 0

chatter:
  requestToBridgeTopic: "wavem/atcplus/ros/chatter"
  responseFromBridgeTopic: "wavem/atcplus/rms/chatter"
  qos: 0